// ================================================================
// main.dart  —  Mukammal Pakistan Party
// App entry-point with SharedPreferences login persistence
// ================================================================

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:mukammalpakistanparty/screens/nav/main_nav_screen.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Screens
import 'package:mukammalpakistanparty/screens/auth/login_screen.dart';
import 'package:mukammalpakistanparty/screens/home/home_screen.dart';

// firebase_options.dart is generated by `flutterfire configure`
import 'firebase_options.dart';

// ================================================================
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── 1. Firebase init ──────────────────────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ── 2. System UI overlay style ────────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarBrightness: Brightness.dark,
    statusBarIconBrightness: Brightness.light,
  ));

  // ── 3. Determine initial route from SharedPreferences ─────────
  final Widget homeWidget = await _resolveStartScreen();

  runApp(MukammalPakistanPartyApp(home: homeWidget));
}

// ── Decide whether to show Login or Home ─────────────────────
Future<Widget> _resolveStartScreen() async {
  // Check SharedPreferences first (fast, local)
  final prefs = await SharedPreferences.getInstance();
  final bool savedLoggedIn = prefs.getBool('isLoggedIn') ?? false;

  // Also verify Firebase still has a valid session (auth truth source)
  final firebaseUser = FirebaseAuth.instance.currentUser;

  if (savedLoggedIn && firebaseUser != null) {
    // Both checks pass → go directly to Home
    return const MainNavScreen();
  }

  // Mismatch or no session → clear prefs and show Login
  await prefs.clear();
  return const LoginScreen();
}

// ================================================================
//  APP SHELL
// ================================================================
class MukammalPakistanPartyApp extends StatelessWidget {
  final Widget home;
  const MukammalPakistanPartyApp({super.key, required this.home});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Mukammal Pakistan Party',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF0D6B35),
          brightness: Brightness.dark,
        ),
        // Remove default splash/highlight so custom taps look polished
        splashColor:     Colors.transparent,
        highlightColor:  Colors.transparent,
      ),
      home: home,
    );
  }
}

// ================================================================
//  LOGIN SCREEN  —  Save session to SharedPreferences on success
// ================================================================
//
//  In your login_screen.dart, after a successful Firebase sign-in,
//  call this helper to persist the session:
//
//    await SessionManager.saveSession();
//
// ================================================================
abstract class SessionManager {
  /// Call this immediately after a successful Firebase sign-in.
  static Future<void> saveSession() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('isLoggedIn', true);
    // Optionally persist UID for quick lookups:
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid != null) await prefs.setString('uid', uid);
  }

  /// Call this on logout (home_screen.dart already calls prefs.clear()).
  static Future<void> clearSession() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.clear();
  }
}